L = [
    "FreezeRaël",
    "Horsligne",
    "ScelléPart.2",
    "Tarkov",
    "Rapcatéchisme",
    "Stretch4",
    "Pasderefrain",
    "BigPharma",
    "LogoAudi",
    "Moncler",
    "RIPPopSmoke",
    "L’artdelaguerre",
    "Numérologie",
    "Danslesbuissons",
    "Desiigner",
    "PDM",
    "ChenLaden",
    "Intro",
    "JeremyLin",
    "3Planètes",
    "Lester",
    "LRH",
    "Fentanyl",
    "SO_CongoPart.2",
    "FredoSantana",
    "BatonRouge",
    "SacrificedeMasse",
    "DonquixoteDoflamingo",
    "MW2",
    "IsshinAshina",
    "Shavkat",
    "AmériqueduSud",
    "Ancelotti",
    "TseChiLop",
    "Kpop",
    "L’hommeméthode",
    "BillClinton",
    "Voldemort",
    "Argentnoirpart.3",
    "Jourdeplus",
    "Lamborghinibénie",
    "CashMoney",
    "Éclipse"
]



for song in L:
    path = "./dataset/freeze_corleone"
    print("node main.js "+song+" > "+path+"/"+song+".txt")